name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yarn
        run: |
          sudo apt update
          sudo apt install npm
          sudo npm install -g yarn
      - name: Install dependencies
        run: |
          yarn add --dev jsdoc@3.6.11 tui-jsdoc-template
      - name: Build doc
        run: |
          yarn docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs